{{- $namespaces := (datasource "namespaces") -}}
{{- $config := (datasource "config") -}}
receivers:
  otlp:
    protocols:
      http:
        auth:
          authenticator: lumigoauth/server
        include_metadata: true # Needed by `headers_setter/lumigo`
{{- range $i, $namespace := $namespaces }}
  k8sanalytics/ns_{{ $namespace.name }}:
    namespace: {{ $namespace.name }}
{{- end }}
{{- range $i, $namespace := $namespaces }}
  k8sobjects/objects_ns_{{ $namespace.name }}:
    auth_type: serviceAccount
    objects:
{{- range $i, $mode := (coll.Slice "watch" "pull") }}
    - name: pods
      mode: {{ $mode }}
      interval: 10m
      namespaces: [ {{ $namespace.name }} ]
    - name: daemonsets
      group: apps
      mode: {{ $mode }}
      interval: 10m
      namespaces: [ {{ $namespace.name }} ]
    - name: deployments
      group: apps
      mode: {{ $mode }}
      interval: 10m
      namespaces: [ {{ $namespace.name }} ]
    - name: replicasets
      group: apps
      mode: {{ $mode }}
      interval: 10m
      namespaces: [ {{ $namespace.name }} ]
    - name: statefulsets
      group: apps
      mode: {{ $mode }}
      interval: 10m
      namespaces: [ {{ $namespace.name }} ]
    - name: cronjobs
      group: batch
      mode: {{ $mode }}
      interval: 10m
      namespaces: [ {{ $namespace.name }} ]
    - name: jobs
      group: batch
      mode: {{ $mode }}
      interval: 10m
      namespaces: [ {{ $namespace.name }} ]
{{- end }}
{{- end }}
{{- range $i, $namespace := $namespaces }}
  k8sobjects/events_ns_{{ $namespace.name }}:
    auth_type: serviceAccount
    objects:
{{- range $i, $mode := (coll.Slice "watch" "pull") }}
{{- range $j, $fieldSelector := (coll.Slice "involvedObject.apiVersion=v1,involvedObject.kind=Pod" "involvedObject.apiVersion=apps/v1,involvedObject.kind=DaemonSet" "involvedObject.apiVersion=apps/v1,involvedObject.kind=Deployment" "involvedObject.apiVersion=apps/v1,involvedObject.kind=ReplicaSet" "involvedObject.apiVersion=apps/v1,involvedObject.kind=StatefulSet" "involvedObject.apiVersion=batch/v1,involvedObject.kind=CronJob" "involvedObject.apiVersion=batch/v1,involvedObject.kind=Job" ) }}
    - name: events
      mode: {{ $mode }}
      interval: 10m
      namespaces: [ {{ $namespace.name }} ]
      field_selector: {{ $fieldSelector }},involvedObject.uid!='' # Filter out events without the involved object's UID, e.g., the ones generated by our webhook
{{- end }}
{{- end }}
{{- end }}

extensions:
  health_check:
  headers_setter/lumigo:
    headers:
    # Use the same authorization header as the one accompanying
    # the request received in the receiver. It needs the
    # `include_metadata: true` parameter in the `otlp` exporter
    - key: authorization
      from_context: Authorization
      action: upsert
  lumigoauth/server:
    type: server
{{- range $i, $namespace := $namespaces }}
  lumigoauth/ns_{{ $namespace.name }}:
    type: client
    token: {{ $namespace.token }}
{{- end }}

exporters:
  otlphttp/lumigo:
    endpoint: {{ env.Getenv "LUMIGO_ENDPOINT" "https://ga-otlp.lumigo-tracer-edge.golumigo.com" }}
    auth:
      authenticator: headers_setter/lumigo
{{- if $config.debug }}
  logging:
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1
{{- end }}
{{- range $i, $namespace := $namespaces }}
  otlphttp/lumigo_ns_{{ $namespace.name }}:
    endpoint: $LUMIGO_ENDPOINT
    auth:
      authenticator: lumigoauth/ns_{{ $namespace.name }}
{{- end }}

processors:
  k8sdataenricherprocessor:
    auth_type: serviceAccount
{{- range $i, $namespace := $namespaces }}
  transform/add_ns_attributes_ns_{{ $namespace.name }}:
    log_statements:
    - context: resource
      statements:
      - set(attributes["k8s.namespace.name"], "{{ $namespace.name }}")
      - set(attributes["k8s.namespace.uid"], "{{ $namespace.uid }}")
{{- end }}
  filter/only_monitored_namespaces:
    error_mode: ignore
    logs:
      include:
        match_type: regexp
        resource_attributes:
        # We add k8s.namespace.name in the 'transform/add_ns_attributes_ns_<$namespace.name>' processor
{{- $namespaceNames := slice }}
{{- range $i, $namespace := $namespaces }}
{{- $namespaceNames = $namespaceNames | append $namespace.name }}
{{- end }}
        - key: k8s.namespace.name
          value: "{{ join $namespaceNames "|" }}"
  transform/add_heartbeat_attributes:
    log_statements:
    - context: scope
      statements:
      - set(name, "lumigo-operator.namespace_heartbeat")
  transform/set_k8s_objects_scope:
    log_statements:
    - context: scope
      statements:
      - set(name, "lumigo-operator.k8s-objects")
      - set(version, "{{ $config.operator.version }}")
  transform/set_k8s_events_scope:
    log_statements:
    - context: scope
      statements:
      - set(name, "lumigo-operator.k8s-events")
      - set(version, "{{ $config.operator.version }}")
{{- range $i, $namespace := $namespaces }}
  batch/k8s_objects_ns_{{ $namespace.name }}:
    send_batch_size: 100
    timeout: 1s
  batch/k8s_events_ns_{{ $namespace.name }}:
    send_batch_size: 100
    timeout: 1s
{{- end }}
  transform/inject_operator_details_into_resource:
    trace_statements:
    - context: resource
      statements:
      - set(attributes["lumigo.k8s_operator.version"], "{{ $config.operator.version }}")
      - set(attributes["lumigo.k8s_operator.deployment_method"], "{{ $config.operator.deployment_method }}")
#   metric_statements:
#   - context: resource
#     statements:
#     - set(attributes["lumigo.k8s_operator.version"], "{{ $config.operator.version }}")
#     - set(attributes["lumigo.k8s_operator.deployment_method"], "{{ $config.operator.deployment_method }}")
    log_statements:
    - context: resource
      statements:
      - set(attributes["lumigo.k8s_operator.version"], "{{ $config.operator.version }}")
      - set(attributes["lumigo.k8s_operator.deployment_method"], "{{ $config.operator.deployment_method }}")

service:
  telemetry:
    logs:
      level: {{ ternary $config.debug "debug" "info" }}
  extensions:
  - headers_setter/lumigo
  - health_check
  - lumigoauth/server
{{- range $i, $namespace := $namespaces }}
  - lumigoauth/ns_{{ $namespace.name }}
{{- end }}
  pipelines:
    traces:
      # We cannot add a Batch processor to this pipeline as it would break the
      # `headers_setter/lumigo` extension.
      # See https://github.com/open-telemetry/opentelemetry-collector/issues/4544
      receivers:
      - otlp
      processors:
      - k8sdataenricherprocessor
      - transform/inject_operator_details_into_resource
      exporters:
      - otlphttp/lumigo
{{- if $config.debug }}
      - logging
{{- end }}
{{- range $i, $namespace := $namespaces }}
    logs/usage_analytics_ns_{{ $namespace.name }}:
      receivers:
      - k8sanalytics/ns_{{ $namespace.name }}
      processors:
      - transform/add_heartbeat_attributes
      - transform/add_ns_attributes_ns_{{ $namespace.name }}
      - transform/inject_operator_details_into_resource
      exporters:
{{- if $config.debug }}
      - logging
{{- end }}
      - otlphttp/lumigo_ns_{{ $namespace.name }}
    logs/k8s_objects_ns_{{ $namespace.name }}:
      receivers:
      - k8sobjects/objects_ns_{{ $namespace.name }}
      processors:
      - transform/set_k8s_objects_scope
      - k8sdataenricherprocessor
      - transform/add_ns_attributes_ns_{{ $namespace.name }}
      - filter/only_monitored_namespaces
      - transform/inject_operator_details_into_resource
      - batch/k8s_objects_ns_{{ $namespace.name }}
      exporters:
{{- if $config.debug }}
      - logging
{{- end }}
      - otlphttp/lumigo_ns_{{ $namespace.name }}
    logs/k8s_events_ns_{{ $namespace.name }}:
      receivers:
      - k8sobjects/events_ns_{{ $namespace.name }}
      processors:
      - transform/set_k8s_events_scope
      - k8sdataenricherprocessor
      - transform/add_ns_attributes_ns_{{ $namespace.name }}
      - filter/only_monitored_namespaces
      - transform/inject_operator_details_into_resource
      - batch/k8s_events_ns_{{ $namespace.name }}
      exporters:
{{- if $config.debug }}
      - logging
{{- end }}
      - otlphttp/lumigo_ns_{{ $namespace.name }}
{{ end }}
