ignore:
  # Only required until gomplate is released with https://github.com/hairyhenderson/gomplate/issues/1960 resolved
  # TODO: Remove this once the above issue is resolved
  - vulnerability: GHSA-449p-3h89-pw88
  - vulnerability: GHSA-mw99-9chc-xw7r
