---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: injector-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: injector-webhook-service
      namespace: system
      path: /v1alpha1/inject
  failurePolicy: Ignore
  admissionReviewVersions:
  - v1
  - v1beta1
  name: lumigoinjector.kb.io
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - daemonsets
    - deployments
    - replicasets
    - statefulsets
  - apiGroups:
    - batch
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cronjobs
    - jobs
  sideEffects: None
