---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: webhooks-service
    app.kubernetes.io/instance: webhooks-service
    app.kubernetes.io/component: lumigo
    app.kubernetes.io/created-by: lumigo
    app.kubernetes.io/part-of: lumigo
    app.kubernetes.io/managed-by: kustomize
  name: webhooks-service
  namespace: system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: controller-manager
  type: ClusterIP
