apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-telemetry-proxy-service
  labels:
  {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: telemetry-proxy
    app.kubernetes.io/created-by: lumigo
    app.kubernetes.io/part-of: lumigo
    control-plane: controller-manager
spec:
  type: {{ .Values.metricsService.type }}
  selector:
  {{- include "helm.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
  ports:
  - name: otlphttp
    protocol: TCP
    # TODO Can we use generated certificates to make it HTTPS?
    # If we used self-signed certs, how would we pass the CA to OTLP exporters in client apps?
    port: 80
    targetPort: otlphttp

