apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchdog
  namespace: system
  labels:
    control-plane: watchdog
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: watchdog
    app.kubernetes.io/component: watchdog
    app.kubernetes.io/created-by: lumigo
    app.kubernetes.io/part-of: lumigo
    app.kubernetes.io/managed-by: kustomize
    lumigo.auto-trace: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: watchdog
  template:
    metadata:
      labels:
        control-plane: watchdog
        lumigo.auto-trace: "false"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      securityContext:
        runAsNonRoot: true
        fsGroup: 1234
      serviceAccountName: controller-manager
      containers:
        - name: watchdog
          image: host.docker.internal:5000/watchdog:latest
          command: ["/watchdog"]
          env:
            - name: LUMIGO_OPERATOR_VERSION
              value: latest
            - name: LUMIGO_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LUMIGO_METRICS_ENDPOINT
              value: https://ga-otlp.lumigo-tracer-edge.golumigo.com
            - name: LUMIGO_LOGS_ENDPOINT
              value: https://ga-otlp.lumigo-tracer-edge.golumigo.com
            - name: LUMIGO_DEBUG
              value: "false"
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1234