{{ if and .Values.lumigoToken .Values.monitoredNamespaces }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm.fullname" . }}-install-hook
  labels:
  {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: lumigo
    app.kubernetes.io/part-of: lumigo
    control-plane: controller-manager
    lumigo.auto-trace: 'false' # We do not need the operator to inject itself
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded # we skip hook-failed, so the job will be kept for troubleshooting in case of a failure
spec:
  completions: 1
  backoffLimit: 2
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
      {{- include "helm.selectorLabels" . | nindent 8 }}
        lumigo.auto-trace: 'false' # We do not need the operator to inject itself
        control-plane: controller-manager
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: 120 # Unfortunately, as of v3.11, Helm does not expose to templates its own timeout
      containers:
      - name: install-hook
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag | default .Chart.AppVersion }}
        command:
          - "/manager"
        args:
          - --quickstart={{ .Values.monitoredNamespaces | toJson }}
          - --lumigo-token={{ .Values.lumigoToken.value }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
        fsGroup: 1234
      serviceAccountName: lumigo-kubernetes-operator
{{- end }}